// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQEghuNbJiV3fEbDM2_cRqEFfDtRazm9E',
    appId: '1:325599984560:web:cc82a9d25c5a97dae73475',
    messagingSenderId: '325599984560',
    projectId: 'googa-17e45',
    authDomain: 'googa-17e45.firebaseapp.com',
    storageBucket: 'googa-17e45.firebasestorage.app',
    measurementId: 'G-6W2QFNF4PW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUF_iIiasjxF39L8oOgtKkdZyFfojVgJc',
    appId: '1:325599984560:android:90dc55c3113a40fae73475',
    messagingSenderId: '325599984560',
    projectId: 'googa-17e45',
    storageBucket: 'googa-17e45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD97UXVU90_Y2iAeV5Zc-IhZ8sek2mRIxw',
    appId: '1:325599984560:ios:00893b0303cbee0ae73475',
    messagingSenderId: '325599984560',
    projectId: 'googa-17e45',
    storageBucket: 'googa-17e45.firebasestorage.app',
    iosBundleId: 'com.example.messPrototype',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD97UXVU90_Y2iAeV5Zc-IhZ8sek2mRIxw',
    appId: '1:325599984560:ios:00893b0303cbee0ae73475',
    messagingSenderId: '325599984560',
    projectId: 'googa-17e45',
    storageBucket: 'googa-17e45.firebasestorage.app',
    iosBundleId: 'com.example.messPrototype',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQEghuNbJiV3fEbDM2_cRqEFfDtRazm9E',
    appId: '1:325599984560:web:fb1ea56c89d07ad6e73475',
    messagingSenderId: '325599984560',
    projectId: 'googa-17e45',
    authDomain: 'googa-17e45.firebaseapp.com',
    storageBucket: 'googa-17e45.firebasestorage.app',
    measurementId: 'G-N9256M37VE',
  );
}
