"""add file access control

Revision ID: 45d22debc949
Revises: 2ea4d6c38754
Create Date: 2026-08-15 18:00:29.736845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45d22debc949'
down_revision: Union[str, Sequence[str], None] = '2ea4d6c38754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_access_file_id'), 'file_access', ['file_id'], unique=False)
    op.create_index(op.f('ix_file_access_id'), 'file_access', ['id'], unique=False)
    op.create_index(op.f('ix_file_access_user_id'), 'file_access', ['user_id'], unique=False)

    file_access_type = sa.Enum(
        'PRIVATE',
        'SHARED',
        'PUBLIC',
        name='file_access_type'
    )
    file_access_type.create(op.get_bind(), checkfirst=True)

    op.add_column('files', sa.Column('access_type', file_access_type, nullable=False, server_default='PRIVATE'))

    op.alter_column(
        'files',
        'access_type',
        server_default=None
    )

    op.add_column('files', sa.Column('allow_forward', sa.Boolean(), nullable=False, server_default=sa.true()))

    op.alter_column(
        'files',
        'allow_forward',
        server_default=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_access_user_id'), table_name='file_access')
    op.drop_index(op.f('ix_file_access_id'), table_name='file_access')
    op.drop_index(op.f('ix_file_access_file_id'), table_name='file_access')
    op.drop_table('file_access')
    op.drop_column('files', 'allow_forward')
    op.drop_column('files', 'access_type')
    # ### end Alembic commands ###
