"""add user presence and last seen

Revision ID: 891493fe61ca
Revises: ffe3ff031f70
Create Date: 2026-08-12 11:42:42.113306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '891493fe61ca'
down_revision: Union[str, Sequence[str], None] = 'ffe3ff031f70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    user_presence = sa.Enum(
        'ONLINE',
        'OFFLINE',
        name='user_presence'
    )

    user_presence.create(
        op.get_bind(),
        checkfirst=True
    )


    op.add_column('users', sa.Column('presence', user_presence, nullable=True))
    op.add_column('users', sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True))

    op.execute("UPDATE users SET presence='OFFLINE'")

    op.alter_column(
        'users',
        'presence',
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen')
    op.drop_column('users', 'presence')
    # ### end Alembic commands ###
