"""add file storage fields

Revision ID: 988128d3ff35
Revises: 5ab2d3f0de8c
Create Date: 2026-08-15 15:03:53.980441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '988128d3ff35'
down_revision: Union[str, Sequence[str], None] = '5ab2d3f0de8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('path', sa.String(length=500), nullable=False))
    op.add_column('files', sa.Column('stored_name', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'files', ['stored_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='unique')
    op.drop_column('files', 'stored_name')
    op.drop_column('files', 'path')
    # ### end Alembic commands ###
